[workspace]
members = ["openaleph-api", "openaleph-tui"]
resolver = "2"

# The profile that 'cargo dist' will build with
[profile.dist]
inherits = "release"
lto = "thin"

[workspace.metadata.release]
publish = false
push = true
tag = true
pre-release-hook = [
  "git",
  "cliff",
  "-o",
  "CHANGELOG.md",
  "--tag",
  "{{version}}",
]

[workspace.metadata.dist.github-custom-runners]
aarch64-apple-darwin = "macos-14"
aarch64-unknown-linux-gnu = "ubuntu-22.04"
aarch64-pc-windows-msvc = "ubuntu-22.04"
x86_64-apple-darwin = "macos-14"
x86_64-unknown-linux-gnu = "ubuntu-22.04"
x86_64-unknown-linux-musl = "ubuntu-22.04"
x86_64-pc-windows-msvc = "ubuntu-22.04"
global = "ubuntu-22.04"

[workspace.package]
version = "0.5.0"
edition = "2021"
repository = "https://github.com/stchris/aleph-tui"
homepage = "https://github.com/stchris/aleph-tui"
license = "GPL-3.0-or-later"

[workspace.lints.clippy]
unwrap_used = "deny"
